apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
 - rollout.yaml
 - template.yaml
images:
- name: opsmxdev/issuegen
  newTag: v3.0.6
namePrefix: opsmx-
 
commonLabels:
 owner : purushotham
